Traceback (most recent call last):
  File "/home/oz/.local/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 295, in _evaluate
    first_sample = next(iter(self.inputset))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oz/.local/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 462, in compile
    self._evaluate("Compiling", inputset)
  File "/home/oz/.local/lib/python3.10/site-packages/concrete/fhe/compilation/compiler.py", line 301, in _evaluate
    raise RuntimeError(message) from error
RuntimeError: Compiling function 'add' without an inputset is not supported
